### ISSUE TITLE
correct version referencing in version.c

### ISSUE THREAD

**Issue by zandbelt** [cisco/cjose#16]
as far as I understand:
https://github.com/cisco/cjose/blob/master/src/version.c#L12

should read:
````
    return JOSE_VERSION;
````
instead of:
````
    return VERSION;
````
since the former is generated by:
https://github.com/cisco/cjose/blob/master/include/cjose/version.h.in#L25
````
#define CJOSE_VERSION "@PACKAGE_VERSION@"
````
which also makes the testing slightly more relevant at:
https://github.com/cisco/cjose/blob/master/test/check_version.c#L21
````
START_TEST (test_cjose_version_fn)
{
    const char *version = cjose_version();
    ck_assert_str_eq(version, VERSION);
}
END_TEST
````
as `VERSION` is obtained from the compiler settings if I'm correct; I may misunderstand what the intent of it is though

**Comment by linuxwolf** [comment]
Since CJOSE_VERSION and VERSION are equivalent, it doesn't matter.

However, using CJOSE_VERSION would protect against any future where VERSION and CJOSE_VERSION.
