### ISSUE TITLE
recompile with -fPIC

### ISSUE THREAD

**Issue by baniani** [cisco/cjose#29]
make give me this error message:

...
/usr/bin/ld: /usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libjansson.a(dump.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-amazon-linux/4.8.3/../../../../lib64/libjansson.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[1]: **\* [libcjose.la] Error 1

Any idea how to fix it?

**Comment by zandbelt** [comment]
Your libjose and libjansson should either both be either shared libraries or static libraries, you can't mix the two. It would be best to compile libjansson as a shared library first.

**Comment by linuxwolf** [comment]
As @zandbelt states, mixing and matching static vs shared libraries is not a supported configuration by most.

Best to either go all static or all shared.
