### ISSUE TITLE
cjose_jws_verify should not release resources on errors

### ISSUE THREAD

**Issue by zandbelt** [cisco/cjose#31]
The current implementation of `cjose_jws_verify` releases the allocated JWS resources when the verification fails for some reason, see e.g.: https://github.com/cisco/cjose/blob/master/src/jws.c#L1169

Firstly I've found this to be counter-intuitive from a developer perspective.

Secondly it makes the calling code having to differentiate between error paths and successful paths wrt. releasing resources.

Thirdly, it makes it impossible to call `cjose_jws_verify` in a loop for a number of keys e.g. in scenario's where no `kid` is presented in the JWS header but a number of verification keys have been pre-configured.

**Comment by jobol** [comment]
> Firstly I've found this to be counter-intuitive from a developer perspective.

much more than agreed

**Comment by linuxwolf** [comment]
Sorry for the delayed response.

I agree the behavior should be the same regardless of return value.  Unless someone has a PR ready, can see about addressing this in the next week.
