### ISSUE TITLE
test_cjose_jws_self_sign_self_verify fails on s390x

### ISSUE THREAD

**Issue by christmart** [cisco/cjose#38]
While building cjose for Debian the test on s390x fails:

check_jws.c:81:F:core:test_cjose_jws_self_sign_self_verify:0: cjose_jws_sign failed: crypto error, file: jws.c, function: _cjose_jws_build_sig_rs, line: 536
check_jws.c:81:F:core:test_cjose_jws_self_sign_self_verify_short:0: cjose_jws_sign failed: crypto error, file: jws.c, function: _cjose_jws_build_sig_rs, line: 536
check_jws.c:81:F:core:test_cjose_jws_self_sign_self_verify_empty:0: cjose_jws_sign failed: crypto error, file: jws.c, function: _cjose_jws_build_sig_rs, line: 536
check_jws.c:81:F:core:test_cjose_jws_self_sign_self_verify_many:0: cjose_jws_sign failed: crypto error, file: jws.c, function: _cjose_jws_build_sig_rs, line: 536

I don't see a memory problem.

**Comment by linuxwolf** [comment]
@christmart can you provide some information on how OpenSSL is packaged for s390x?  Failures here could also be due to the lack of EC support being compiled in.

We'll work on a way to get more detailed errors reported from OpenSSL otherwise.

**Comment by zandbelt** [comment]
@linuxwolf the errors occur in a build of 0.4.1 which was released before reformatting; so jws.c:536  refers to this line: 
https://github.com/cisco/cjose/blob/67eba4845a31853d8f4986fa93659437801d2771/src/jws.c#L536

**Comment by linuxwolf** [comment]
@zandbelt @christmart there are only three ways for cjose_base64url_encode to fail:

1. memory errors
2. NULL or 0 input
3. NULL outputs


The jws.c code definitely prevents #3 from happening, which leaves either memory errors or bad inputs.  I think I recall some versions of OpenSSL with EC features compiled out would not return errors, but might not return values either.

**Comment by christmart** [comment]
Hi Matthiew

Am 04.01.2017 um 20:58 schrieb Matthew A. Miller:
> @christmart <https://github.com/christmart> can you provide some
> information on how OpenSSL is packaged for s390x? Failures here could
> also be due to the lack of EC support being compiled in.
> 
> We'll work on a way to get more detailed errors reported from OpenSSL
> otherwise.

openssl was build on Debian with:

> ./Configure --prefix=/usr --openssldir=/usr/lib/ssl --libdir=lib/s390x-linux-gnu no-idea no-mdc2 no-rc5 no-zlib  enable-tlsext no-ssl2 no-ssl3 enable-unit-test no-ssl3-method enable-rfc3779 enable-cms debian-s390x
> Configuring for debian-s390x
>     no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128 (skip dir)
>     no-gmp          [default]  OPENSSL_NO_GMP (skip dir)
>     no-idea         [option]   OPENSSL_NO_IDEA (skip dir)
>     no-jpake        [experimental] OPENSSL_NO_JPAKE (skip dir)
>     no-krb5         [krb5-flavor not specified] OPENSSL_NO_KRB5
>     no-libunbound   [experimental] OPENSSL_NO_LIBUNBOUND (skip dir)
>     no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
>     no-mdc2         [option]   OPENSSL_NO_MDC2 (skip dir)
>     no-rc5          [option]   OPENSSL_NO_RC5 (skip dir)
>     no-sctp         [default]  OPENSSL_NO_SCTP (skip dir)
>     no-shared       [default] 
>     no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE (skip dir)
>     no-ssl2         [option]   OPENSSL_NO_SSL2 (skip dir)
>     no-ssl3         [option(ssl)] OPENSSL_NO_SSL3 (skip dir)
>     no-ssl3-method  [option(ssl)] OPENSSL_NO_SSL3_METHOD (skip dir)
>     no-store        [experimental] OPENSSL_NO_STORE (skip dir)
>     no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS (skip dir)
>     no-zlib         [option]  
>     no-zlib-dynamic [default] 
> IsMK1MF=0
> CC            =gcc
> CFLAG         =-DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DB_ENDIAN -g -O2 -fdebug-prefix-map=/«PKGBUILDDIR»=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wa,--noexecstack -Wall
> EX_LIBS       =-ldl
> CPUID_OBJ     =mem_clr.o
> BN_ASM        =bn_asm.o
> EC_ASM        =
> DES_ENC       =des_enc.o fcrypt_b.o
> AES_ENC       =aes_core.o aes_cbc.o
> BF_ENC        =bf_enc.o
> CAST_ENC      =c_enc.o
> RC4_ENC       =rc4_enc.o rc4_skey.o
> RC5_ENC       =rc5_enc.o
> MD5_OBJ_ASM   =
> SHA1_OBJ_ASM  =
> RMD160_OBJ_ASM=
> CMLL_ENC      =camellia.o cmll_misc.o cmll_cbc.o
> MODES_OBJ     =
> ENGINES_OBJ   =
> PROCESSOR     =
> RANLIB        =/usr/bin/ranlib
> ARFLAGS       =
> PERL          =/usr/bin/perl
> SIXTY_FOUR_BIT_LONG mode
> DES_UNROLL used
> DES_INT used
> RC4 uses uchar
> RC4_CHUNK is unsigned long


-- 
============================================================================
Christoph Martin, Leiter Unix-Systeme
Zentrum für Datenverarbeitung, Uni-Mainz, Germany
 Anselm Franz von Bentzel-Weg 12, 55128 Mainz
 Telefon: +49(6131)3926337
 Instant-Messaging: Jabber: martin@uni-mainz.de
  (Siehe http://www.zdv.uni-mainz.de/4010.php)

**Comment by christmart** [comment]
Hi,

maybe this is a hint about the problems with build on s390x.

Christoph

**Comment by christmart** [comment]
The attachement of the previous message is missing.

I got the following hint from Aurelien Jarno <aurelien@aurel32.net>:

Looking at the failures, it seems to fails on all 64-bit big-endian
architectures (ppc64, s390x, sparc64). Looking at the code, there is
an issue with at least this part of the code from jws.c:

    if (RSA_sign(digest_alg, jws->dig, jws->dig_len, jws->sig, (unsigned int *)&jws->sig_len, (RSA *)jwk->keydata) != 1)

You can't cast a pointer to a pointer of different size.

**Comment by linuxwolf** [comment]
Thanks for the hint.  I don't see anything in the openssl configuration items that point to a particular problem.  That line is certainly a bug that should be addressed, but I have no way to confirm it's the cause of *this* issue.

**Comment by christmart** [comment]
Am 20.01.2017 um 17:46 schrieb Matthew A. Miller:
> Thanks for the hint. I don't see anything in the openssl configuration
> items that point to a particular problem. That line is certainly a bug
> that should be addressed, but I have no way to confirm it's the cause of
> /this/ issue.

If you have a fix for this, I can test if it helps for the original problem.

-- 
============================================================================
Christoph Martin, Leiter Unix-Systeme
Zentrum für Datenverarbeitung, Uni-Mainz, Germany
 Anselm Franz von Bentzel-Weg 12, 55128 Mainz
 Telefon: +49(6131)3926337
 Instant-Messaging: Jabber: martin@uni-mainz.de
  (Siehe http://www.zdv.uni-mainz.de/4010.php)

**Comment by christmart** [comment]
The patch is working and also fixes the problem with the failing test after building on s390x, sparc64 and ppc64.
