### ISSUE TITLE
autoreconf --force --install on CentOs 6.7 have warning message

### ISSUE THREAD

**Issue by uhnaf** [cisco/cjose#39]
Hi,
    It's great library!
automake version: 1.14
autoconf version: 2.69

Execute autoreconf --force --install have warning message:
configure.ac:9: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body

**Comment by DRAKUN** [comment]
yum install autoconf automake gcc gcc-c++ git libtool make nasm pkgconfig zlib-devel
