### ISSUE TITLE
Got 'openssl/obj_mac.h' file not found error when installing mod_auth_openidc

### ISSUE THREAD

**Issue by ekarudianto** [cisco/cjose#42]
Been trying to use this library to install mod_auth_openidc since this software is a dependency for it, all runnning well untill I tried to run 'make', I got this error

> clang: warning: /usr/local/opt/cjose/include: 'linker' input unused
In file included from src/mod_auth_openidc.c:74:
In file included from src/mod_auth_openidc.h:60:
In file included from src/jose.h:64:
In file included from /usr/local/include/cjose/cjose.h:26:
/usr/local/include/cjose/jwk.h:20:10: fatal error: 'openssl/obj_mac.h' file not found
#include <openssl/obj_mac.h>
         ^
1 error generated.
apxs:Error: Command failed with rc=65536
.
make: *** [src/mod_auth_openidc.la] Error 1

Below is my environment setup

- Apache (2.4.25)
- cjose (latest)
- OpenSSL (OpenSSL 1.0.2j  26 Sep 2016)
- Curl
- Jansson (2.9)
- pcre3 (8.39)
- pkg-config (0.29.1_2)
- hiredis (0.13.3)

*note that all software is installed using Brew (don't know if it will be matter just put some informations together)

Below is my ./configure setup on mod_auth_openidc

> erudianto$ CJOSE_CFLAGS=/usr/local/opt/cjose/include CJOSE_LIBS=/usr/local/opt/cjose/lib ./configure --with-apxs2=/Users/erudianto/Downloads/apache-server/dist/bin/apxs --prefix /Users/erudianto/Downloads/mod_auth_openidc-2.1.3/dist

**Comment by linuxwolf** [comment]
On macOS with Homebrew, by default OpenSSL is not `link`ed, which mean the build very well may be pulling in the platform's install (OpenSSL 0.9.8zh).

You can force the distro of OpenSSL using `--with-openssl` as mentioned in the README.md:

```
CJOSE_CFLAGS=/usr/local/opt/cjose/include CJOSE_LIBS=/usr/local/opt/cjose/lib ./configure --with-apxs2=/Users/erudianto/Downloads/apache-server/dist/bin/apxs --prefix /Users/erudianto/Downloads/mod_auth_openidc-2.1.3/dist --with-openssl=/usr/local/opt/openssl
```

**Comment by ekarudianto** [comment]
actually it's a problem with the mod_auth it self so I made some modification on it, thanks for the help tho @linuxwolf
