### ISSUE TITLE
yes/lib is throwing off libtool

### ISSUE THREAD

**Issue by veselov** [cisco/cjose#45]
Version: 0.4.1
If configured with jansson and/or openssl, there is a '-Lyes/lib' LD_FLAG that is added, that freaks out the libtool.
```
[vps@phoenix]~/src/cjose$ ./configure --prefix=/opt/soft/cjose --exec-prefix=/opt/soft/cjose 
...
[vps@phoenix]~/src/cjose$ make -j
... <all OK> ...
[vps@phoenix]~/src/cjose$ ./configure --prefix=/opt/soft/cjose --exec-prefix=/opt/soft/cjose --with-jansson --with-openssl
...
[vps@phoenix]~/src/cjose$ make -j
...
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 --pedantic -Wall -Werror -g -O2 -I../include -g -O2 -Iyes/include/ -Iyes/include/ -lm -Lyes/lib -Lyes/lib -o libcjose.la -rpath /opt/soft/cjose/lib libcjose_la-version.lo libcjose_la-util.lo libcjose_la-base64.lo libcjose_la-jwk.lo libcjose_la-jwe.lo libcjose_la-jws.lo libcjose_la-header.lo libcjose_la-error.lo  -ljansson -lcrypto 
../libtool: line 7472: cd: yes/lib: No such file or directory
libtool:   error: cannot determine absolute directory name of 'yes/lib'
Makefile:438: recipe for target 'libcjose.la' failed
[vps@phoenix]~/src/cjose$ grep 'yes/lib' * 2>/dev/null 
config.log:configure:14829: gcc -o conftest -g -O2 -Iyes/include/  -Iyes/include/  -Lyes/lib conftest.c -lcrypto   >&5
config.log:configure:14911: gcc -o conftest -g -O2 -Iyes/include/ -Iyes/include/  -Iyes/include/ -Iyes/include/  -Lyes/lib -Lyes/lib conftest.c -ljansson  -lcrypto  >&5
config.log:LDFLAGS=' -Lyes/lib -Lyes/lib'
config.status:S["LDFLAGS"]=" -Lyes/lib -Lyes/lib"
Makefile:LDFLAGS =  -Lyes/lib -Lyes/lib
```

**Comment by zandbelt** [comment]
The `--with-jansson --with-openssl` flags need a value that specifies where the respective libraries are found: 
````
./configure --help | grep with
  --disable-option-checking  ignore unrecognized --enable/--with options
  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
  --with-pic[=PKGS]       try to use only PIC/non-PIC objects [default=use
  --with-aix-soname=aix|svr4|both
  --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
  --with-sysroot[=DIR]    Search for dependent libraries within DIR (or the
  --with-openssl          Location where OpenSSL can be found
  --with-jansson          Location where Jansson can be found
````
I guess it should have said:
````
  --with-openssl[=DIR]          Location where OpenSSL can be found
  --with-jansson[=DIR]          Location where Jansson can be found
````

**Comment by veselov** [comment]
Right. It'd be cool if the use of those options without an argument is somehow prevented. Otherwise, configure, I guess, just gives them a "yes" value. Is there a particular reason to not use standard way of configure discovering the libraries?

**Comment by zandbelt** [comment]
I don't think there is...

**Comment by veselov** [comment]
There is PKG_CHECK_MODULES macro that uses pkg-config. Then it deals with all the flags as well. There will be a change to the configure syntax, because I don't see how you can provide custom path at the same time. But one can still provide custom path by adding necessary environment vars. I can post a PR if you're interested.

**Comment by linuxwolf** [comment]
The flag choices were based on the state of autotools recommendations we could find when this project started.

I'm not sure what exactly the benefit this PR is supposed to add.  OpenSSL and Jansson are not optional dependencies.

**Comment by veselov** [comment]
IMHO, one would typically have OpenSSL/Jansson installed as devel packages. So one wouldn't use package paths, and just use /usr. Using pkg-config returns all kinds of cflags and ldflags that the maintainer wants you to use, not just -I/-L/-l.

**Comment by linuxwolf** [comment]
We have users that need to be explicit about what instance (or API-compatible instance) of OpenSSL (and Jansson) they are using.  Maybe we could have gone with envars, but we didn't.
