### ISSUE TITLE
memory leak found by valgrind

### ISSUE THREAD

**Issue by gangwan123** [cisco/cjose#50]
Our project is using the cjose library. When running valgrind for our project, we found a definitely loss issue in cjose. We check our codes and make sure that the memory of cjose_jws_t is released by calling method cjose_jws_release. So I wonder if the memory of jws->dig is leaked in in some cases. Could you please help check this problem?
Valgrind logs
==26157== 32 bytes in 1 blocks are definitely lost in loss record 15 of 61
==26157==    at 0x40272B2: malloc (vg_replace_malloc.c:270)
==26157==    by 0x88D4C4D: _cjose_jws_build_dig_sha (jws.c:218)
==26157==    by 0x88D35BE: cjose_jws_verify (jws.c:1159)
==26157==    by 0x88CA701: wbx_ci_self_contained_token_validate::TokenValidateSig::VerifyByKey(std::string const&, _cjose_jws_int*) (token_validate_sig.cpp:87)

**Comment by zandbelt** [comment]
I'm using valgrind on cjose, its test suite and my own application and haven't found such a leak. Therefore I'd say that your calling code doesn't release properly on all possible paths.

**Comment by linuxwolf** [comment]
I've not seen this myself, and lacking of any other evidence, I'm closing this.
