### ISSUE TITLE
Memory leak when cjose_jws_verify is called second time on same jws

### ISSUE THREAD

**Issue by BilalChughtai** [cisco/cjose#72]
I noticed that if I call cjose_jws_verify a second time, memory is leaked.

==5109== 32 bytes in 1 blocks are definitely lost in loss record 183 of 280
==5109==    at 0x4C29F13: malloc (vg_replace_malloc.c:299)
==5109==    by 0x546C0C7: _cjose_jws_build_dig_sha (jws.c:176)
==5109==    by 0x546D962: cjose_jws_verify (jws.c:1052)

Is this known / expected? and should the application always discard JWS before a second attempt to verify the JWS?

**Comment by linuxwolf** [comment]
Fixed by commit 425dfcfd4a84f646564f69afbbd46e900caa21e9
