### ISSUE TITLE
Compile for iOS

### ISSUE THREAD

**Issue by emartynov** [cisco/cjose#79]
Guys, can you add documentation section how to compile lib for iOS?

**Comment by garnaizd** [comment]
./configure --with-openssl=/usr/local/openssl-1.0.2j –with-jansson=/usr/local/opt/jansson & make

**Comment by garnaizd** [comment]
It's fine for you @emartynov ?

**Comment by emartynov** [comment]
Sure, but should it be part of README?

**Comment by garnaizd** [comment]
Yes @emartynov .
This library can be build for several architectures. And developers don't have to know in this case how to build for iOS architectures or others.

I fought a lot to find how to build static libraries for iOS. We could help more people if it is added in a README.
I will generate a pull request.

Regards

**Comment by emartynov** [comment]
I'm not ios developer but was looking to the library and I was not able to match knowledge of make file with the linking for iOS.

Thank you!

**Comment by drewpitchford** [comment]
@garnaizd Could you post the library here for us to include directly into our projects?

**Comment by deepesh-vasthimal-cko** [comment]
From where do i get the .a file mentioned on the script. Please help 

`cp -p src/.libs/libcjose.a ${PREFIX}/lib/libcjose.a`

**Comment by deepesh-vasthimal-cko** [comment]
> #!/bin/bash
> 
> export DEVROOT=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
> DFT_DIST_DIR=${HOME}/libcjose-ios-dist
> DIST_DIR=${DIST_DIR:-$DFT_DIST_DIR}
> 
> function build_for_arch() {
> ARCH=$1
> HOST=$2
> SYSROOT=$3
> PREFIX=$4
> IPHONEOS_DEPLOYMENT_TARGET="9.0"
> 
> echo "**************Building cjose for ${ARCH}****"
> 
> #Openssl
> export libcrypto_LIBS="-L/Users/gemma/Desktop/xcode/dependencies/OpenSSL/lib -lcrypto"
> export libcrypto_CFLAGS="-I/Users/gemma/Desktop/xcode/dependencies/OpenSSL/include"
> #export libcrypto_LIBS="-L/usr/local/opt/openssl/lib -lcrypto"
> #export libcrypto_CFLAGS=-I/usr/local/opt/openssl/include
> 
> #Jannson
> export jansson_LIBS="-L/Users/gemma/jansson2.8/lib -ljansson"
> export jansson_CFLAGS="-I/Users/gemma/jansson2.8/include"
> 
> export PATH="${DEVROOT}/usr/bin/:${PATH}"
> export CFLAGS="-arch ${ARCH} -pipe -Os -gdwarf-2 -isysroot ${SYSROOT} -miphoneos-version-min=${IPHONEOS_DEPLOYMENT_TARGET} -fembed-bitcode"
> export LDFLAGS="-arch ${ARCH} -isysroot ${SYSROOT}"
> 
> make clean
> ./configure --host="${HOST}" -with-openssl="/Users/gemma/Desktop/xcode/dependencies/OpenSSL" --with-jansson="/Users/gemma/jansson2.8" && make
> echo "_********Configure finished********_"
> mkdir -p ${PREFIX}/lib/
> cp -p src/.libs/libcjose.a ${PREFIX}/lib/libcjose.a
> 
> }
> 
> TMP_DIR=/tmp/build_libcjose_$$
> 
> build_for_arch i386 i386-apple-darwin /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk ${TMP_DIR}/i386 || exit 1
> build_for_arch x86_64 x86_64-apple-darwin /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk ${TMP_DIR}/x86_64 || exit 2
> #build_for_arch armv7s armv7s-apple-darwin /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk ${TMP_DIR}/armv7s || exit 4
> build_for_arch armv7 armv7-apple-darwin /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk ${TMP_DIR}/armv7 || exit 5
> build_for_arch arm64 arm-apple-darwin /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk ${TMP_DIR}/arm64 || exit 3
> mkdir -p ${TMP_DIR}/lib/
> 
> ${DEVROOT}/usr/bin/lipo
> -arch i386 ${TMP_DIR}/i386/lib/libcjose.a
> -arch x86_64 ${TMP_DIR}/x86_64/lib/libcjose.a
> -arch armv7 ${TMP_DIR}/armv7/lib/libcjose.a
> -arch arm64 ${TMP_DIR}/arm64/lib/libcjose.a
> -output ${TMP_DIR}/lib/libcjose.a -create
> 
> mkdir -p ${DIST_DIR}/include
> cp -p /usr/local/include/cjose/*.h ${DIST_DIR}/include
> cp -r ${TMP_DIR}/lib ${DIST_DIR}


How can i install the open ssl for xcode, jansson2.8 and from where can i get libcjose.a
